-- auto-generated definition
create table if not exists dbtransactionentity
(
    id                bigint generated by default as identity
        primary key,
    balance           numeric(100, 19),
    blocknumber       bigint,
    confirmstatus     varchar(255),
    fromaddress       varchar(255),
    hash              varchar(255),
    toaddress         varchar(255),
    transactionstatus varchar(255),
    unit              varchar(255)
);

alter table dbtransactionentity
    owner to admin;



-- auto-generated definition
create table if not exists walletentity
(
    id                bigint generated by default as identity
        primary key,
    address           varchar(255),
    balance           numeric(100, 19),
    balanceunit       varchar(255),
    pendingwithdrawal numeric(100, 19),
    privatekey        varchar(255)
);

alter table walletentity
    owner to admin;

-- auto-generated definition
create table if not exists blockcounterentity
(
    id          bigint generated by default as identity
        primary key,
    blocknumber bigint,
    createdate  timestamp
);

alter table blockcounterentity
    owner to admin;

